# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-XZtWD6koJSvDy3dunIVqRTB8yR-u6U
"""

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

# Leer datos
car_data = pd.read_csv("vehicles_us.csv")

# Título
st.header("Análisis de anuncios de venta de vehículos")

# Botón Histograma
hist_button = st.button("Construir histograma")

if hist_button:

    st.write("Histograma del odómetro")

    fig = go.Figure(
        data=[go.Histogram(x=car_data["odometer"])]
    )

    fig.update_layout(
        title="Distribución del Odómetro",
        xaxis_title="Kilómetros",
        yaxis_title="Cantidad"
    )

    st.plotly_chart(fig, use_container_width=True)

# Botón Scatter
scatter_button = st.button("Construir gráfico de dispersión")

if scatter_button:

    st.write("Relación entre precio y kilometraje")

    fig = go.Figure(
        data=[go.Scatter(
            x=car_data["odometer"],
            y=car_data["price"],
            mode="markers"
        )]
    )

    fig.update_layout(
        title="Precio vs Odómetro",
        xaxis_title="Kilómetros",
        yaxis_title="Precio"
    )

    st.plotly_chart(fig, use_container_width=True)